In [1]:
install.packages("dlm")
library(dlm)


The downloaded binary packages are in
	/var/folders/qr/y9jw5mv175zf8hcs038xchyc0000gn/T//RtmpapXMaz/downloaded_packages


In [2]:
data.url<-"https://raw.githubusercontent.com/iwanami-datascience/vol1/master/matsuura/example2/input/data-season.txt"
data<-read.csv(url(data.url))
Y<-data$Y

In [3]:
dlm.build4 <- function(par){
    mod <- dlmModPoly(order=1)+dlmModSeas(frequency=4)
    V(mod) <- exp(par[1])
    diag(W(mod))[1:2] <- exp(par[2:3])
    m0(mod) <- c(20,0,0,0)
    return(mod)
}
dlm.mle4 <- dlmMLE(Y,parm=rep(0,3),build=dlm.build4)
dlm.mod4 <- dlm.build4(dlm.mle4$par)

In [4]:
FF(dlm.mod4)

[,1] [,2] [,3] [,4]
[1,] 1    1    0    0

In [5]:
GG(dlm.mod4)

[,1] [,2] [,3] [,4]
[1,] 1     0    0    0  
[2,] 0    -1   -1   -1  
[3,] 0     1    0    0  
[4,] 0     0    1    0

In [6]:
V(dlm.mod4)

[,1]        
[1,] 4.402579e-07

In [7]:
W(dlm.mod4)

[,1]      [,2]      [,3] [,4]
[1,] 0.4470163 0.0000000 0    0   
[2,] 0.0000000 0.4115065 0    0   
[3,] 0.0000000 0.0000000 0    0   
[4,] 0.0000000 0.0000000 0    0

In [8]:
dlmLL(Y,dlm.mod4)

[1] 68.4441

In [9]:
dlm.fil4 <- dlmFilter(Y,dlm.mod4)
dlm.for4 <- dlmForecast(dlm.fil4, nAhead=8)

In [10]:
head(dlm.for4$f,3)

[,1]    
[1,] 24.01961
[2,] 32.72886
[3,] 20.71521

In [11]:
head(dlm.for4$a,3)

[,1]     [,2]      [,3]      [,4]     
[1,] 25.08242 -1.062813 -2.216420 -4.367209
[2,] 25.08242  7.646442 -1.062813 -2.216420
[3,] 25.08242 -4.367209  7.646442 -1.062813

In [12]:
head(unlist(dlm.for4$Q))

[1] 2.077538 2.226197 2.514896 2.611079 4.688616 4.837275

In [13]:
## TODO 図2のプロット #7